### ISSUE TITLE
Support for Screen share

### ISSUE THREAD

**Issue by Raj123456788** [Gruveo/gruveo-ios-sdk#1]
Will this library support screen sharing for ios?

**Comment by artmatsak** [comment]
The SDK supports displaying incoming screen sharing feed from desktop. Sharing of the iOS device's screen (outgoing screen sharing) is currently not supported.

**Comment by Raj123456788** [comment]
Thank you for the reply. Any idea when it will be supported?

**Comment by artmatsak** [comment]
Unfortunately, no timeline for this at this point.

**Comment by Raj123456788** [comment]
Has the functionality been added to iOS_webrtc repo? Any info on this is appreciated!

**Comment by artmatsak** [comment]
I haven't been able to find any references to this in the WebRTC issue tracker. I very much doubt that iOS screen capturing is there though. As an example, iOS 8 opened access to the H.264 hardware encoder and decoder back in 2014, but support in WebRTC landed in production only ~2 years later.

**Comment by Raj123456788** [comment]
https://bugs.chromium.org/p/webrtc/issues/detail?id=7177

Don't know, how much we can make out this forum.
