### ISSUE TITLE
Is It possible to customize calling screen?

### ISSUE THREAD

**Issue by ahmadmuhsink** [Gruveo/gruveo-ios-sdk#2]
I am interested in using Gruveo but I really need to customize calling screen for our product to be usable and I didnt see that in current API, isnt it?

another thing we need to look up is possibility to disable chat completely because we already have our own chat system.

**Comment by artmatsak** [comment]
The SDK is an out-of-the-box solution and so you can't do many modifications to the call UI. What exactly are you trying to achieve though?

**Comment by ahmadmuhsink** [comment]
What I need is only the video call solution. So I need to disable the chat because we already have our own chat system. Rest is fine though

**Comment by artmatsak** [comment]
I see. Unfortunately, there's currently no way to disable the in-call text chat. We might look into it though.

**Comment by ahmadmuhsink** [comment]
I see. Thanks for quick response.
