### ISSUE TITLE
How to get whose end the call?

### ISSUE THREAD

**Issue by ikki08** [Gruveo/gruveo-ios-sdk#3]
Hello, right now my application will use Gruveo as video call service. But some how we need to know whose end the call and I couldn't find that at current gruveo SDK. Or I missing some thing?

**Comment by artmatsak** [comment]
Hi, do you need to know which participant ended the call?

**Comment by ikki08** [comment]
Yes, my app need that but some how I can't find how to do it in mobile sdk.

**Comment by mgurkivskyi** [comment]
Hi, we added new `GruveoCallEndReasonOtherParty` to `GruveoCallEndReason` enum in GruveoSDK 1.1, new version is available on CocoaPods.
