### ISSUE TITLE
Connection issue pop up on call end

### ISSUE THREAD

**Issue by ahmadmuhsink** [Gruveo/gruveo-ios-sdk#6]
Gruveo iOS SDK version: v1.1.1

I got "Connection Issue" popup whenever the call end, despite its never the case, because the other party end the call intentionally.
this popup is not appear on 1.0.1 version but appear on 1.1.0 as well
so maybe still related with callEstablished issue : https://github.com/Gruveo/gruveo-ios-sdk/issues/4

![image uploaded from ios](https://user-images.githubusercontent.com/8171574/32536735-3d759fe0-c492-11e7-911e-4ff7d17487e3.jpg)

Reproduce:
Call as usual, make sure other party end the call not ours.

**Comment by artmatsak** [comment]
Version 1.1 of the SDK added automatic call reconnection. What's happening here is that when the other participant hangs up, the WebRTC connection fails before we receive a hangup event from the signaling server. Hence the client briefly shows a "Connection issues" message.

We are looking into ways to mitigate this.
