### ISSUE TITLE
iOS SDK Stoping Music when calling GruveoCallManager.setClientId

### ISSUE THREAD

**Issue by cesariel** [Gruveo/gruveo-ios-sdk#9]
When Spotify or another Music Player is playing a music, when you call the setClientId on the App Delegate, is stoping the music. How can I fixed this issue?

**Comment by artmatsak** [comment]
Thanks for reporting this, we're looking into the issue.

**Comment by artmatsak** [comment]
@cesariel Are you able to reproduce this with our [sample app](https://github.com/Gruveo/gruveo-ios-sdk/tree/master/Example)?
